# https://github.com/khusika/FeelIt/blob/main/exampleSite/config.toml
baseURL = "https://168bearsafety.com"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "zh-tw"
# language code
languageCode = "zh-tw"
title = "交通平安熊安全"

# Change the default theme to be use when building the site with Hugo
theme = "FeelIt"

[params]
# FeelIt theme version
images = ["https://i.imgur.com/Dm60.jpg"]
version = "1.0.X"

[params.footer]
enable = true
# Custom content (HTML format is supported)
custom = '168bearsafety'
# whether to show Hugo and theme info
hugo = true
# whether to show copyright info
copyright = true
# whether to show the author
author = true
# site creation time
since = 2022
# license info (HTML format is supported)

[languages]
[languages.zh-tw]
weight = 1
# language code
languageCode = "zh-tw"
# language name
languageName = "中文"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = true
# default amount of posts in each pages
paginate = 12
# copyright description used only for seo schema
# copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
# Menu config
[languages.zh-tw.menu]
[[languages.zh-tw.menu.main]]
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
name = "文章"
post = ""
url = "/posts/"
# title will be shown when you hover on this menu link.
title = ""
weight = 1
[[languages.zh-tw.menu.main]]
identifier = "tags"
name = "標籤"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[languages.zh-tw.menu.main]]
identifier = "categories"
name = "分類"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 3
[[languages.zh-tw.menu.main]]
identifier = "about"
name = "關於"
post = ""
pre = ""
title = ""
url = "/about/"
weight = 4
[[languages.zh-tw.menu.main]]
identifier = "facebook"
name = ""
post = ""
pre = "<i class='fab fa-facebook fa-fw'></i>"
title = "Facebook"
url = "https://www.facebook.com/168bearsafety"
weight = 6
# [[languages.zh-tw.menu.main]]
# identifier = "Instagram"
# name = ""
# post = ""
# pre = "<i class='fab fa-brands fa-instagram'></i>"
# title = "Instagram"
# url = ""
# weight = 6
[languages.zh-tw.params]
# site description
description = "臺灣的交通安全部落格"
# site keywords
keywords = ["交通安全", "臺灣", "熊安全"]


# Home page config
[languages.zh-tw.params.home]
# amount of RSS pages
rss = 10
# Home page profile
[languages.zh-tw.params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = ""
# URL of avatar shown in home page
avatarURL = "/images/avatar.webp"
# title shown in home page (HTML format is supported)
title = ""
# subtitle shown in home page (HTML format is supported)
subtitle = "提昇臺灣的交通安全是熊安全的夢想"
# whether to use typeit animation for subtitle
typeit = false
# whether to show social links
social = true
# disclaimer (HTML format is supported)
disclaimer = ""
# Home page posts

[languages.zh-tw.params.home.posts]
enable = true
# special amount of posts in each home posts page
# paginate = 6
# display image-preview
imagePreview = true

[languages.zh-tw.params.page]
fraction = true
ruby = true
fontawesome = false

# Markup related configuration in Hugo
[markup]
# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false is a necessary configuration (https://github.com/khusika/FeelIt/issues/158)
noClasses = false

[privacy]
# privacy of the Google Analytics
[privacy.googleAnalytics]
anonymizeIP = false
disable = false
respectDoNotTrack = true
useSessionStorage = false
